server:
  address: "localhost"
  port: 3306

database:
  db_user: "root"
  db_password: "asd"

logger:
  log_directory: "/mnt/d/databases/mysql/resources/mysql-restore-dump-with-prefix/test"
  log_filename: "restore.log"

software:
  destination_prefix: "eff0887_"
  restore_threads: 4
  ## "<path-to-dump-file1>,<path-to-dump-file2>,.."
  dump_file_directorys: "/mnt/d/databases/mysql/resources/MySQL-Data-Migration-and-Renaming"


